pipeline {
    agent any
    parameters {
        string(name: 'SERVER_IP', defaultValue: '', description: 'Enter the IP address of the target server')
        string(name: 'Username', defaultValue: 'gouravsingh335', description: 'Enter username for  login')
    }
    environment {
        SSH_CREDENTIALS_ID = 'ssh-user-key' // Replace with your Jenkins SSH credentials ID
        INSTALL_SCRIPT = './install-script.sh'  // Update with the path to your installation script
    }
    stages {
        stage('Validate Input') {
            steps {
                script {
                    if (params.SERVER_IP == '') {
                        error("SERVER_IP parameter is required.")
                    }
                }
            }
        }
          stage('Run Installation Script') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'ssh-user-key', keyFileVariable: 'SSH_CREDENTIALS_ID')]) {
                    script {
                        // Start ssh-agent and add the key
                        sh """
                        eval \$(ssh-agent -s)
                        ssh-add ${SSH_KEY_FILE}
                        """

                        // Transfer and run the script
                        sh """
                        scp -o StrictHostKeyChecking=no ${INSTALL_SCRIPT} ${SSH_USER}@${params.SERVER_IP}:/tmp/install-script.sh
                        ssh -o StrictHostKeyChecking=no ${SSH_USER}@${params.SERVER_IP} "GIT_TOKEN=${params.GIT_TOKEN} bash /tmp/install-script.sh"
                        """
                    }
                }
            }
        }
    }
    post {
        success {
            echo "Installation script executed successfully on ${SERVER_IP}."
        }
        failure {
            echo "Failed to run the installation script on ${SERVER_IP}."
        }
    }
}
